### ISSUE TITLE
UX Feature request - QR code to scan

### ISSUE THREAD

**Issue by mrceperka** [ekzhang/bore#127]
Hello,

just wanted to put my first thought I had while using `bore`. 

Everything worked quite nice but the effort to navigate to the website on the mobile phone could be improved.
Obviously this is minor issue but for less experienced users it would make easier to use `bore`

My suggestion is to **print QR code to the console when starting the new tunnel**.

**Comment by ekzhang** [comment]
I'm closing because additional options are not in scope for bore. It's a small program and meant to be read/forked if you have more particular use cases.

I don't have the resources to maintain a general-purpose tool, and I think something like this is better built for your specific use case regardless
