### ISSUE TITLE
Configureable timeout

### ISSUE THREAD

**Issue by solonovamax** [ekzhang/bore#129]
I'm having issues where I need a longer timeout than 3 seconds (weird network I don't control)

It would be nice to have a `--timeout` parameter or something to configure the timeout.

**Comment by ekzhang** [comment]
I'm closing because additional options are not in scope for bore. It's a small program and meant to be read/forked if you have more particular use cases.

I don't have the resources to maintain a general-purpose tool, and I think something like this is better built for your specific use case regardless

**Comment by solonovamax** [comment]
adding a cli flag to set the timeout should be quite simple though, no?

**Comment by ekzhang** [comment]
Once again, you're welcome to fork the project
