### ISSUE TITLE
the bore.pub server appears to be inaccessible for us

### ISSUE THREAD

**Issue by LaurelineLogiaco** [ekzhang/bore#133]
Hi,

Thanks for sharing and supporting bore, it's a great tool!

Recently (for a few days), my colleague and I have been unable to connect to bore.pub. We are having this issue from several MIT servers, as well as from personal desktops.

Here is an example of what we get in response to the bore command below:

`bore local 13334 --to bore.pub
Error: could not connect to bore.pub:7835

Caused by:
    timed out
`

If the bore.pub server is down, do you expect it to be back up - and if so, when would it be? Else, if you have an idea of what we're doing wrong, we'll be happy to hear feedback!

**Comment by ekzhang** [comment]
Hi @LaurelineLogiaco — I don't believe bore.pub is down, I just tried it and it works. Just shooting off ideas, but do you have a `dig` or `traceroute` output?

**Comment by sunnyddelight** [comment]
Hi @ekzhang, 
I'm working with @LaurelineLogiaco. I ran some tests and it seems like its some issues on our end since we can't reach the bore.pub servers from the MIT network. This seems to be a recent change since until recently we were using the tool fine. I tested this on my laptop off network and it seems to work fine but when we're on the campus network both ping and traceroute time out but we are able to resolve dns fine with dig. 
```
; <<>> DiG 9.18.28-0ubuntu0.22.04.1-Ubuntu <<>> bore.pub
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52465
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;bore.pub.			IN	A

;; ANSWER SECTION:
bore.pub.		1075	IN	A	159.223.171.199

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53) (UDP)
;; WHEN: Wed Sep 25 13:23:08 EDT 2024
;; MSG SIZE  rcvd: 53
```
This seems like something changed in the firewall or something. Open to other suggestions if you think its something else but happy to close this issue otherwise.

**Comment by ekzhang** [comment]
Sounds good. Feel free to send your `traceroute` output as well. That's unfortunate but I guess maybe a network administrator has blocked the IP.

**Comment by ekzhang** [comment]
Okay yeah looks like it's getting blocked within MIT network! Can't fix that.
