### ISSUE TITLE
bore to lan

### ISSUE THREAD

**Issue by Addvilz** [ekzhang/bore#14]
Would be very useful if it would be possible to provide not only local tunnel, but also a tunnel to LAN, to expose something behind a router/FW. ngrok supports this as well.

**Comment by ekzhang** [comment]
Hey, thanks for the suggestion! Usually I would not consider "ngrok supports this" as a justification for inclusion in `bore` because ngrok is production software-as-a-service, while bore is intended to be minimal and therefore intentionally limited in scope. However I think this is a reasonable suggestion and would just involve passing a single configuration string to the client, which defaults to `localhost`.
