### ISSUE TITLE
Does this work to forward minecraft server traffic?

### ISSUE THREAD

**Issue by DillFrescott** [ekzhang/bore#20]
Minecraft Java uses TCP

**Comment by ekzhang** [comment]
Yeah, it should work if you just forward the port that your server's listening on. That said I wouldn't recommend it since you usually want a stable IP and uptime guarantees for a Minecraft server, so that players can always connect. Bore (and your connection to bore) would be a single point of failure.

**Comment by DillFrescott** [comment]
Gotcha! Thank you for the information!
