### ISSUE TITLE
installation via brew

### ISSUE THREAD

**Issue by Kikobeats** [ekzhang/bore#27]
Hello, I really love the project; Thanks for crafting it 🙂 

Is any chance to make it possible to install via [brew](https://brew.sh/)? 

This will be helpful to reduce the installation friction, especially for non Rust developers.

**Comment by ekzhang** [comment]
Unfortunately I haven't gotten to that yet, although packaging contributions along this vein are welcome.

**Comment by ekzhang** [comment]
Very long overdue, but I finally got around to learning how Homebrew formulas work. You can now install bore via brew on macOS!

```
brew install ekzhang/bore/bore
```

<img width="942" alt="Screen Shot 2022-06-05 at 1 03 54 PM" src="https://user-images.githubusercontent.com/7550632/172061817-a9f00208-1af7-486d-90f7-f1dd7c1647ad.png">

**Comment by orhun** [comment]
> I finally got around to learning how Homebrew formulas work.

Was it harder than you expected? What's your take on it?

**Comment by ekzhang** [comment]
Honestly there's not a lot of documentation, and I probably did it wrong. The official formulas for rust projects like [exa](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/exa.rb) and [ripgrep](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/ripgrep.rb) seem interesting, they have a description of how to build the CLI from source and a "bottle" system that shares pre-built binaries for each platform, as well as a DSL for system dependencies and test runners.

Mine was a [super simple formula](https://github.com/ekzhang/homebrew-bore/blob/main/Formula/bore.rb) though, which downloads the tar.gz and doesn't support `brew install ... --head`. I needed a `uname -m` hack because on my M1 Mac the Homebrew Ruby's `RbConfig` object was still displaying `x86_64` for some reason.
