### ISSUE TITLE
Provide GitHub release binaries / artifacts via CI

### ISSUE THREAD

**Issue by takase1121** [ekzhang/bore#6]
I'm not sure the exact details but I know this can be done. This'll simplify a lot of things for those who don't have rust installed.

**Comment by ekzhang** [comment]
Thanks for the suggestion! I’d love to do this as well and am open to any contributions from people who would like to help set this up.

There’s other Rust CLI tools like ripgrep, exa, and dust. Glancing at their deployment pipelines the binary step seems pretty complicated, involving a lot of configuration that I don’t understand, cross-compilation, various linking toolchains, etc. I’m also not sure what tools to use: cargo-cross, cargo-zigbuild, etc.

So I might not do binary releases myself given my lack of knowledge here, since it would take some time to learn. It’s also unclear to me how many people would use bore as a daily tool, which also impacts my decision — right now, doesn’t seem like many people.

**Comment by WladyX** [comment]
Would also like to see some Dockerfile for the server.
Thanks for sharing this!

**Comment by praveenperera** [comment]
@ekzhang I'll do this

**Comment by shaxxx** [comment]
Can someone provide the binaries until CI/CD pipeline is ready? 
As far as I can tell pipeline does produce binaries but only tests are failing?

**Comment by praveenperera** [comment]
@shaxxx tests are passing now with: https://github.com/ekzhang/bore/pull/35

@ekzhang will merge in when he releases the next version. For now you can pretty easily create them with `cargo`, or grab them from here: https://github.com/praveenperera/bore/releases/tag/v0.0.2
