### ISSUE TITLE
UDP forwarding support

### ISSUE THREAD

**Issue by DUOLabs333** [ekzhang/bore#9]
Will this support UDP? It looks great, but I want to be able to forward some of my UDP-based services.

**Comment by ekzhang** [comment]
Good question! It's a fair point and good use case. There are a couple ways we could forward UDP:

1. Send UDP datagrams over the TCP control connection as individual messages. This is the simplest approach and wouldn't require changing the architecture of the system, since we sidestep the UDP hole punching / NAT passthrough issue. However, this is inefficient and negates the advantage of using a protocol like UDP in the first place, rather than TCP. It also requires setting up auxiliary local UDP listener to handle return messages and proxying those over TCP as well, with the correct metadata attached to route the datagram to the correct remote return address.
2. Send regular empty UDP messages from the local client to the server ([hole punching](https://en.wikipedia.org/wiki/UDP_hole_punching)), then forward UDP datagrams directly. This is more efficient than sending UDP data over TCP, but it's slightly more complex to get right. It also breaks UDP datagrams sent to the _return address_, since the return address would just be the server in this case, and the server has no way of telling who the return message is destined for.

So there's quite a bit of design choices / opinions in forwarding UDP since the nature of the protocol is different. Since the goal of `bore` is to be extremely minimal, I would probably err on the side of not supporting UDP for now. Happy to chat more about this though.

**Comment by ekzhang** [comment]
(Also, just wanted to say for future readers that with attribution, you are welcomed and even _encouraged_ to fork the code and give it a new name! Part of the reason why `bore` is so minimal is to be easy to understand for readers and provide a baseline implementation to inspire your own specialized proxies.)

**Comment by ekzhang** [comment]
Closing this issue due to being out of scope.

**Comment by DillFrescott** [comment]
Hey if anyone wants a good UDP tool check out chisel on github. But since it can bypass firewalls it is flagged as a virus with most antiviruses, but know its not a virus, it just could be used maliciously.
