### ISSUE TITLE
Suggestion: TCP keepalive Support

### ISSUE THREAD

**Issue by CorleoneYang** [ekzhang/bore#91]
Hi, I'm trying to open up a VNC port on my mac so I can remotely access my computer anytime. But I found that if there is no data communication for a long time, the connection will be disconnected after a change in the middle of the network link (the client mistakenly believes that it is now connected). 

Enabling TCP Keepalive can be used to prevent this from happening. Is it possible to add the option of whether to enable tcp keepalive in the parameter？

**Comment by ekzhang** [comment]
Thanks for the suggestion! I don't think we'll add a setting to enable configuring TCP keepalive to bore, since it's intended to be minimal as an example of how to do something like this. But configuring it yourself is easy if you want to modify bore or write your own proxy based on it. You can lower it from the 2 hour default with:

```rust
use socket2::{SockRef, TcpKeepalive};

// ...

impl Server {
    // ...

    /// Start the server, listening for new connections.
    pub async fn listen(self) -> Result<()> {
        let this = Arc::new(self);
        let addr = SocketAddr::from(([0, 0, 0, 0], CONTROL_PORT));
        let listener = TcpListener::bind(&addr).await?;

        SockRef::from(&listener). set_tcp_keepalive(&Duration::from_secs(30)?; // <- new line of code
// ...
```

**Comment by CorleoneYang** [comment]
Eventually I added keepalive to client side and it can reconnect to server automatically. Thanks!
Solution: [add: TcpKeepalive Support](https://github.com/CorleoneYang/bore/commit/f8a3f51dc0b5f7a40fcc893bdb9a92fcecff17e8)
