### ISSUE TITLE
Support reading the secret from a file

### ISSUE THREAD

**Issue by nogweii** [ekzhang/bore#99]
Perhaps as an additional environment variable, `BORE_SECRET_FILE`?

This is for two reasons:

* Environment variables aren't particularly secure against snooping from other processes
* And because of that, `systemd`'s own credential management doesn't support that. The decrypted credential is only available as a file

**Comment by ekzhang** [comment]
I'm closing because additional options are not in scope for bore. It's a small program and meant to be read/forked if you have more particular use cases.

I don't have the resources to maintain a general-purpose tool, and I think something like this is better built for your specific use case regardless
